### ISSUE TITLE
Insert image with Text

### ISSUE THREAD

**Issue by cinder92** [acaziasoftcom/react-native-bottomsheet#6]
Hello thanks for your awesome plugin, is there anyway to insert a text with a `left` or `right` image?

kind of

```
BottomSheet.showBottomSheetWithOptions({
  options: [
    {image : "http:// || require(...)", title : "Option 1", position : "right"},
   {image : "http:// || require(...)", title : "Option 2", position : "left"},
   {image : "http:// || require(...)", title : "Option 3", position : "right"},
  ],
  title: 'Demo Bottom Sheet',
  dark: true,
  cancelButtonIndex: 3,
}, (value) => {
  alert(value);
});
```

**Comment by Doko-Demo-Doa** [comment]
No, not for now because the original ActionSheetIOS doesn't have it also. On Android it is possible but I want it to be consistent across platforms.

**Comment by Noitidart** [comment]
Hi there would it make more sense to be platform consistent, rather then feature consistent?

Because per modal design I am needing to create modals bottom sheet on Android:

https://material.io/guidelines/components/bottom-sheets.html#bottom-sheets-persistent-bottom-sheets

* https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3NWNQcUo1TnhhaWs/components-bottomsheets-modal1.png
* https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3UzA3RDctV2k0YUk/components-bottomsheets-modal2.png
* https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3OWxLQ182ZTNxZGM/components-bottomsheets-modal3.png

Your package is perfect, except if I could just get the Google Material style on Android. :(

**Comment by Noitidart** [comment]
I actually really only need a good Android bottom sheet plugin, for iOS I use Facebooks built in - http://facebook.github.io/react-native/releases/0.49/docs/actionsheetios.html#actionsheetios

Would you be able to help us with a bottom sheet module for Android only that just wrap soarcn's module?

**Comment by Doko-Demo-Doa** [comment]
Yes, possible, not hard, but pretty time-consuming, since I can only make open source native Android modules like this when I have free time (they are non-profit projects anyway).

**Comment by Noitidart** [comment]
Thanks sir for whatever you can do! And the great work you have done so far! Maybe you can team up with the guys here - https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior

They seem to have progressed androdi pretty well and it works down till android 4.1 which is min supported by android

**Comment by Noitidart** [comment]
@Doko-Demo-Doa when doing react-native run-android with this, I get this:

```
   > A problem occurred configuring project ':react-native-bottomsheet'.
      > You have not accepted the license agreements of the following SDK components:
[Android SDK Build-Tools 26.0.2].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
```

Does this mean it requires 26.0.2? I was hoping to support Android 4.1+.

Thanks again for this awesome work.

**Comment by Doko-Demo-Doa** [comment]
Nope. It is the build tool's license agreement only. Check this out:

`https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components`

Or you can open Android Studio, open SDK Manager:

![SDK Manager](https://puu.sh/yqYjy.png)

And tick on it:

![Build Tools](https://puu.sh/yqYwv.png)

**Comment by Noitidart** [comment]
Thank you very very much for such detailed explanation with screenshots! :) This is great news that it still works on 4.1.1! :)
